name: calljmp
description: 'Calljmp SDK for Flutter'
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.calljmp
        pluginClass: CalljmpPlugin
      ios:
        pluginClass: CalljmpPlugin
