name: calljmp
description: 'Calljmp is a secure backend-as-a-service (BaaS) for Flutter apps, with auth, storage, SQL access, and attestation support.'
version: 0.0.6
homepage: https://calljmp.com
repository: https://github.com/Calljmp/calljmp-flutter

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  http_parser: ^4.0.0
  crypto: ^3.0.6
  plugin_platform_interface: ^2.0.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.calljmp
        pluginClass: CalljmpPlugin
      ios:
        pluginClass: CalljmpPlugin
